name: Visa Slot Checker Automation

on:
  schedule:
    - cron: "*/3 * * * *"  # Runs every 3 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libatk1.0-0 \
            libcups2 \
            libgdk-pixbuf2.0-0 \
            libnspr4 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libasound2 \
            libxss1 \
            libxtst6 \
            libappindicator3-1 \
            libatspi2.0-0

      - name: Install Dependencies
        run: npm install

      - name: Install Puppeteer Browser
        run: npx puppeteer browsers install chrome
        env:
          CI: false

      - name: Set Puppeteer Permissions
        run: chmod -R 755 node_modules/puppeteer/.local-chromium

      - name: Run Script
        run: node index.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
