name: Puppeteer Script Automation

on:
  schedule:
    - cron: "*/3 * * * *"  # Runs every 3 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update || true
          sudo apt-get install -y \
            libatk1.0-0 \
            libcups2 \
            libgdk-pixbuf2.0-0 \
            libnspr4 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libasound2 \
            libxss1 \
            libxtst6 \
            libappindicator3-1 \
            libatspi2.0-0 \
            libv4l-0 \
            libv4l2rds0 \
            libv4lconvert0

      - name: Install Dependencies
        run: npm install

      - name: Run Puppeteer Script
        run: node index.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
